dating_libre_app:
    site_name: 'Dating Libre Demo'
    site_description: 'A demonstration of an open source dating platform'
    admin_email: '"Dating Libre" <admin@datinglibre.com>'
    images_bucket: dlibreim
    image_upload: false
    is_demo: true
    payment_providers:
        datinglibre:
            url: https://datinglibre.com
            active: true
    # the values below are limited to alphanumeric characters
    # separated by an underscore. They are used in behat tests
    # and as translation keys. Ansible will generate and run
    # SQL to automatically add them to the database.
    categories:
    - sex
    - relationship
    attributes:
        sex:
        - man
        - woman
        relationship:
        - dominant
        - submissive
        - switch
    interests:
        - music
        - reading
        - sports
        - fitness
    rules:
    - spam
    - abusive_messages
    - offsite_linking
    first_message_require_subscription: true
    testing_user_email_addresses:
    - admin@datinglibre.com

