dating_libre:
    categories:
    - color
    - shape
    attributes:
        color:
        - blue
        - green
        - yellow
        shape:
        - square
        - circle
        - triangle
    block_reasons:
    - no_reason
    - spam
    - abusive