dating_libre_app:
    site_name: 'Dating Libre'
    site_description: 'Description of the site'
    admin_email: '"Dating Libre Staging" <admin@example.com>'
    images_bucket: dlibreim
    image_upload: true
    is_demo: false
    payment_providers:
        datinglibre:
            url: https://datinglibre.com
            active: true
    categories:
    - color
    - shape
    attributes:
        color:
        - blue
        - green
        - yellow
        shape:
        - square
        - circle
        - triangle
    rules:
    - spam
    - abusive_messages

