doctrine:
    dbal:
        types:
            text[]: MartinGeorgiev\Doctrine\DBAL\Types\TextArray
        default_connection: default
        connections:
            default:
                driver: 'pdo_pgsql'
                server_version: '13.3'
                charset: utf8
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    text[]: text[]
                    _text: text[]
                options:
                    # Always use PDO::ATTR_EMULATE_PREPARES as production uses
                    # pgbouncer transaction pool mode, which does not work with
                    # prepared statements
                    20: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App