# Adapted and comments retained from https://github.com/symfony/demo
dist: focal
language: php
php:
  - '7.4'
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.symfony/bin
env:
  global:
    - PATH="$HOME/.symfony/bin:$PATH"
before_install:
  - if symfony self:version; then symfony self:update --yes ; else wget https://get.symfony.com/cli/installer -O - | bash ; fi
install:
  - composer install
  - ./setup.sh
  - symfony serve --port 8000 --no-tls --daemon
script:
  - ./vendor/bin/behat features/ --tags ~javascript